package com.manual.clothing.mapper;

import com.manual.clothing.model.OrderProduct;
import com.manual.clothing.model.OrderProductExample;
import com.manual.clothing.model.OrderProductKey;
import com.manual.clothing.model.OrderProductWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    long countByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int deleteByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(OrderProductKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int insert(OrderProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int insertSelective(OrderProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    List<OrderProductWithBLOBs> selectByExampleWithBLOBs(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    List<OrderProduct> selectByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    OrderProductWithBLOBs selectByPrimaryKey(OrderProductKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") OrderProductWithBLOBs row, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") OrderProductWithBLOBs row, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") OrderProduct row, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OrderProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderProduct row);
}