package com.manual.clothing.mapper;

import com.manual.clothing.model.RoleUsr;
import com.manual.clothing.model.RoleUsrExample;
import com.manual.clothing.model.RoleUsrKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoleUsrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    long countByExample(RoleUsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    int deleteByExample(RoleUsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RoleUsrKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    int insert(RoleUsr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    int insertSelective(RoleUsr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    List<RoleUsr> selectByExample(RoleUsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    RoleUsr selectByPrimaryKey(RoleUsrKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") RoleUsr row, @Param("example") RoleUsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") RoleUsr row, @Param("example") RoleUsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleUsr row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_usr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleUsr row);
}