package com.manual.clothing.model;

public class CustomerWithBLOBs extends Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.gift_code
     *
     * @mbg.generated
     */
    private byte[] giftCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.gift_code
     *
     * @return the value of customer.gift_code
     *
     * @mbg.generated
     */
    public byte[] getGiftCode() {
        return giftCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.gift_code
     *
     * @param giftCode the value for customer.gift_code
     *
     * @mbg.generated
     */
    public void setGiftCode(byte[] giftCode) {
        this.giftCode = giftCode;
    }
}