package com.manual.clothing.model;

import java.util.Date;

public class GiftCode extends GiftCodeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_code.g_code
     *
     * @mbg.generated
     */
    private String gCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_code.del_flg
     *
     * @mbg.generated
     */
    private Byte delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_code.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gift_code.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_code.g_code
     *
     * @return the value of gift_code.g_code
     *
     * @mbg.generated
     */
    public String getgCode() {
        return gCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_code.g_code
     *
     * @param gCode the value for gift_code.g_code
     *
     * @mbg.generated
     */
    public void setgCode(String gCode) {
        this.gCode = gCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_code.del_flg
     *
     * @return the value of gift_code.del_flg
     *
     * @mbg.generated
     */
    public Byte getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_code.del_flg
     *
     * @param delFlg the value for gift_code.del_flg
     *
     * @mbg.generated
     */
    public void setDelFlg(Byte delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_code.create_at
     *
     * @return the value of gift_code.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_code.create_at
     *
     * @param createAt the value for gift_code.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gift_code.update_at
     *
     * @return the value of gift_code.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gift_code.update_at
     *
     * @param updateAt the value for gift_code.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}