package com.manual.clothing.model;

import java.util.Date;

public class Invoice extends InvoiceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.order_at
     *
     * @mbg.generated
     */
    private Date orderAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.invoice_status
     *
     * @mbg.generated
     */
    private String invoiceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.del_flg
     *
     * @mbg.generated
     */
    private Byte delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.customer_id
     *
     * @return the value of invoice.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.customer_id
     *
     * @param customerId the value for invoice.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.order_id
     *
     * @return the value of invoice.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.order_id
     *
     * @param orderId the value for invoice.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.amount
     *
     * @return the value of invoice.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.amount
     *
     * @param amount the value for invoice.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.order_at
     *
     * @return the value of invoice.order_at
     *
     * @mbg.generated
     */
    public Date getOrderAt() {
        return orderAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.order_at
     *
     * @param orderAt the value for invoice.order_at
     *
     * @mbg.generated
     */
    public void setOrderAt(Date orderAt) {
        this.orderAt = orderAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.invoice_status
     *
     * @return the value of invoice.invoice_status
     *
     * @mbg.generated
     */
    public String getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.invoice_status
     *
     * @param invoiceStatus the value for invoice.invoice_status
     *
     * @mbg.generated
     */
    public void setInvoiceStatus(String invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.del_flg
     *
     * @return the value of invoice.del_flg
     *
     * @mbg.generated
     */
    public Byte getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.del_flg
     *
     * @param delFlg the value for invoice.del_flg
     *
     * @mbg.generated
     */
    public void setDelFlg(Byte delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.create_at
     *
     * @return the value of invoice.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.create_at
     *
     * @param createAt the value for invoice.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.update_at
     *
     * @return the value of invoice.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.update_at
     *
     * @param updateAt the value for invoice.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}