package com.manual.clothing.model;

public class InvoiceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invoice.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invoice.id
     *
     * @return the value of invoice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invoice.id
     *
     * @param id the value for invoice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}