package com.manual.clothing.model;

import java.util.Date;

public class OrderProduct extends OrderProductKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.order_at
     *
     * @mbg.generated
     */
    private Date orderAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.del_flg
     *
     * @mbg.generated
     */
    private Byte delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.customer_id
     *
     * @return the value of order_product.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.customer_id
     *
     * @param customerId the value for order_product.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.order_at
     *
     * @return the value of order_product.order_at
     *
     * @mbg.generated
     */
    public Date getOrderAt() {
        return orderAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.order_at
     *
     * @param orderAt the value for order_product.order_at
     *
     * @mbg.generated
     */
    public void setOrderAt(Date orderAt) {
        this.orderAt = orderAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.order_status
     *
     * @return the value of order_product.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.order_status
     *
     * @param orderStatus the value for order_product.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.del_flg
     *
     * @return the value of order_product.del_flg
     *
     * @mbg.generated
     */
    public Byte getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.del_flg
     *
     * @param delFlg the value for order_product.del_flg
     *
     * @mbg.generated
     */
    public void setDelFlg(Byte delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.create_at
     *
     * @return the value of order_product.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.create_at
     *
     * @param createAt the value for order_product.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.update_at
     *
     * @return the value of order_product.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.update_at
     *
     * @param updateAt the value for order_product.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}