package com.manual.clothing.model;

public class OrderProductWithBLOBs extends OrderProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.product
     *
     * @mbg.generated
     */
    private byte[] product;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.product
     *
     * @return the value of order_product.product
     *
     * @mbg.generated
     */
    public byte[] getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.product
     *
     * @param product the value for order_product.product
     *
     * @mbg.generated
     */
    public void setProduct(byte[] product) {
        this.product = product;
    }
}