package com.manual.clothing.model;

import java.util.Date;

public class Payment extends PaymentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.invoice_id
     *
     * @mbg.generated
     */
    private Integer invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.method_payment
     *
     * @mbg.generated
     */
    private String methodPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_status
     *
     * @mbg.generated
     */
    private String paymentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.del_flg
     *
     * @mbg.generated
     */
    private Byte delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.invoice_id
     *
     * @return the value of payment.invoice_id
     *
     * @mbg.generated
     */
    public Integer getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.invoice_id
     *
     * @param invoiceId the value for payment.invoice_id
     *
     * @mbg.generated
     */
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.method_payment
     *
     * @return the value of payment.method_payment
     *
     * @mbg.generated
     */
    public String getMethodPayment() {
        return methodPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.method_payment
     *
     * @param methodPayment the value for payment.method_payment
     *
     * @mbg.generated
     */
    public void setMethodPayment(String methodPayment) {
        this.methodPayment = methodPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_status
     *
     * @return the value of payment.payment_status
     *
     * @mbg.generated
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_status
     *
     * @param paymentStatus the value for payment.payment_status
     *
     * @mbg.generated
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.del_flg
     *
     * @return the value of payment.del_flg
     *
     * @mbg.generated
     */
    public Byte getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.del_flg
     *
     * @param delFlg the value for payment.del_flg
     *
     * @mbg.generated
     */
    public void setDelFlg(Byte delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.create_at
     *
     * @return the value of payment.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.create_at
     *
     * @param createAt the value for payment.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.update_at
     *
     * @return the value of payment.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.update_at
     *
     * @param updateAt the value for payment.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}