package com.manual.clothing.model;

import java.util.Date;

public class Usr extends UsrKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.password_usr
     *
     * @mbg.generated
     */
    private String passwordUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.del_flg
     *
     * @mbg.generated
     */
    private Byte delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.email
     *
     * @return the value of usr.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.email
     *
     * @param email the value for usr.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.password_usr
     *
     * @return the value of usr.password_usr
     *
     * @mbg.generated
     */
    public String getPasswordUsr() {
        return passwordUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.password_usr
     *
     * @param passwordUsr the value for usr.password_usr
     *
     * @mbg.generated
     */
    public void setPasswordUsr(String passwordUsr) {
        this.passwordUsr = passwordUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.role_name
     *
     * @return the value of usr.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.role_name
     *
     * @param roleName the value for usr.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.del_flg
     *
     * @return the value of usr.del_flg
     *
     * @mbg.generated
     */
    public Byte getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.del_flg
     *
     * @param delFlg the value for usr.del_flg
     *
     * @mbg.generated
     */
    public void setDelFlg(Byte delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.create_at
     *
     * @return the value of usr.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.create_at
     *
     * @param createAt the value for usr.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr.update_at
     *
     * @return the value of usr.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr.update_at
     *
     * @param updateAt the value for usr.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
}